name: build-api
on:
  push:
    paths:
      - 'api/**'
      - 'docker-compose.yml'
      - '.github/workflows/build-api.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push API image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/api
          SHA=${{ github.sha }}
          docker build -t $IMAGE:$SHA ./api
          docker push $IMAGE:$SHA
          docker tag $IMAGE:$SHA $IMAGE:prod
          docker push $IMAGE:prod


services:
  api:
    image: ghcr.io/nycounihan/bluecouch/api:prod
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    restart: unless-stopped