## Instructs GitHub Actions how to build the Web Docker image.
## Triggers when push changes to the `web/` folder, `docker-compose.yml`, or this workflow file.
## Checks out the code, logs in to the GitHub Container Registry, builds the image from `web/Dockerfile`,
##  tags it with the commit SHA and `:prod`, and pushes both tags to GHCR.
name: build-web
on:
  push:
    paths:
      - 'web/**'
      - 'docker-compose.yml'
      - '.github/workflows/build-web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push Web image
        run: |
          IMAGE=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/web
          SHA=${{ github.sha }}
          docker build -t $IMAGE:$SHA ./web
          docker push $IMAGE:$SHA
          docker tag $IMAGE:$SHA $IMAGE:prod
          docker push $IMAGE:prod
